config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "static_pages#home"
  devise_for :users

  resources :users do
    resources :avatars, only: [:create] # ajout pour active storage
  end

  resources :orders

  # Static pages
  get "about", to: "static_pages#about"
  get "contact", to: "static_pages#contact"

  resources :items do
    post "add_to_cart", on: :member
  end

  resources :carts do
    delete "remove_item/:item_id", to: "carts#remove_item", on: :member, as: "remove_item"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :description])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :description])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    # Votre code pour l'action home ici
  end

  def login
    # logique pour la page de connexion
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_carousel.html.erb
<div class="container-fluid">
  <div id="carouselExample" class="carousel slide my-custom-carousel mx-auto rounded" style="max-height: 600px; max-width: 800px; overflow: hidden;">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= image_tag('carousel2.jpg', class: 'd-block w-100 img-fluid', alt: '...') %>
      </div>
      <div class="carousel-item">
        <%= image_tag('carousel8.jpg', class: 'd-block w-100 img-fluid', alt: '...') %>
      </div>
      <div class="carousel-item">
        <%= image_tag('carousel3.jpg', class: 'd-block w-100 img-fluid', alt: '...') %>
      </div>
      <div class="carousel-item">
        <%= image_tag('carousel4.jpg', class: 'd-block w-100 img-fluid', alt: '...') %>
      </div>
      <div class="carousel-item">
        <%= image_tag('carousel6.jpg', class: 'd-block w-100 img-fluid', alt: '...') %>
      </div>
      <div class="carousel-item">
        <%= image_tag('carousel7.jpg', class: 'd-block w-100 img-fluid', alt: '...') %>
      </div>
      <div class="carousel-item">
        <%= image_tag('carousel1.jpg', class: 'd-block w-100 img-fluid', alt: '...') %>
      </div>
      <div class="carousel-item">
        <%= image_tag('carousel9.jpg', class: 'd-block w-100 img-fluid', alt: '...') %>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer-custom  bg-primary d-flex ">
  <div class="container text-center py-3">
    <p class="ft">Suivez-nous sur les réseaux sociaux :</p>
    <%= link_to "https://www.facebook.com", class: "btn btn-social btn-facebook btn-lg me-2", target: "_blank", rel: "noopener noreferrer" do %>
      <i class="fab fa-facebook-f"></i> Facebook
    <% end %>
    <%= link_to "https://www.twitter.com", class: "btn btn-social btn-twitter btn-lg me-2", target: "_blank", rel: "noopener noreferrer" do %>
      <i class="fab fa-twitter"></i> Twitter
    <% end %>
    <%= link_to "https://www.instagram.com", class: "btn btn-social btn-instagram btn-lg me-2", target: "_blank", rel: "noopener noreferrer" do %>
      <i class="fab fa-instagram"></i> Instagram
    <% end %>
    <%= link_to "https://www.discord.com", class: "btn btn-social btn-discord btn-lg me-2", target: "_blank", rel: "noopener noreferrer" do %>
      <i class="fab fa-discord"></i> Discord
    <% end %>
    <%= link_to "https://www.github.com", class: "btn btn-social btn-github btn-lg me-2", target: "_blank", rel: "noopener noreferrer" do %>
      <i class="fab fa-github"></i> GitHub
    <% end %>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">The_Chatons_Project</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <!-- Les liens des pages -->
        <li class="nav-item">
          <%= link_to root_path, class: 'nav-link' do %>
            <i class="fas fa-home"></i> Accueil
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to about_path, class: 'nav-link' do %>
            <i class="fas fa-info-circle"></i> Notre équipe
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to contact_path, class: 'nav-link' do %>
            <i class="fas fa-envelope"></i> Contact
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to items_path, class: 'nav-link' do %>
            <i class="fas fa-camera"></i> Nos photos
          <% end %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to user_path(current_user), class: 'nav-link' do %>
              <i class="fas fa-user"></i> Bienvenue, <%= current_user.email %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= button_to destroy_user_session_path, method: :delete, data: { turbo_method: :delete, confirm: "Êtes-vous sûr de vouloir vous déconnecter ?" }, class: "nav-link" do %>
              <i class="fas fa-sign-out-alt"></i> Déconnexion
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: 'nav-link' do %>
              <i class="fas fa-sign-in-alt"></i> Se connecter
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_registration_path, class: 'nav-link' do %>
              <i class="fas fa-user-plus"></i> S'inscrire
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheProjectChat</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <!-- CDN bootstrap -->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
     <!-- CDN FontAwesome - pour les icônes -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
    <!-- Theme: sandstone, origin: bootswtach -->
    <%= stylesheet_link_tag "sandstone", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'style.css' %>
    <!-- CDN javascript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://js.stripe.com/v3/"></script>

  </head>
  <body>
    <!-- Appel de la navbar -->
    <%= render 'layouts/navbar' %>
  
    <div class="content">
      <%= yield %>
    </div>

    <!-- Appel du footer -->
      <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/about.html.erb
<div class="container mt-4 ">
  <h1 class="text-center mb-4">C'est nous l'équipe !</h1>
  <div class="row">
    <!-- Membre 1 : Louis -->
    <div class="col-md-4 mb-4 carrejaune_accueil div">
      <div class="card border rounded">
        <img src="https://cdn.discordapp.com/attachments/1178634390830579752/1179575947125608520/Louis.png?ex=657a48b5&is=6567d3b5&hm=41c3f64d850211c17aee281815dcda72fcaf54b05a2914f6849c07a6a9c277bd&" class="card-img-top rounded-circle" alt="Louis">
        <div class="card-body d-flex flex-column p-3">
          <h5 class="card-title">Louis</h5>
          <p class="card-text flex-grow-1">"Miaou Miaou Mia"</p>
        </div>
      </div>
    </div>
    <!-- Membre 2 : Lala -->
    <div class="col-md-4 mb-4 carrejaune_accueil div">
      <div class="card border rounded">
        <img src="https://cdn.discordapp.com/attachments/1178634390830579752/1179575946563563643/lalaina.png?ex=657a48b5&is=6567d3b5&hm=0a662989648c417e2145960fef256e3dfa924c9f902ea29002e85c64cd32753c&" class="card-img-top rounded-circle" alt="Lala">
        <div class="card-body d-flex flex-column p-3">
          <h5 class="card-title">Lala</h5>
          <p class="card-text flex-grow-1">"Mia Mia Miaou"</p>
        </div>
      </div>
    </div>
    <!-- Membre 3 : Mathieu -->
    <div class="col-md-4 mb-4 carrejaune_accueil div">
      <div class="card border rounded ">
        <img src="https://cdn.discordapp.com/attachments/1178634390830579752/1179575947935092846/Mathieu.png?ex=657a48b5&is=6567d3b5&hm=b238da0cedbf2c9c34d3abc6a8b2ce116b1ffda541cf1f98a4c268b128cd6487&" class="card-img-top rounded-circle" alt="Mathieu">
        <div class="card-body d-flex flex-column p-3">
          <h5 class="card-title">Mathieu</h5>
          <p class="card-text flex-grow-1">"Miaou Miaou Miaou"</p>
        </div>
      </div>
    </div>
    <!-- Membre 4 : Flo -->
    <div class="col-md-4 mb-4 carrejaune_accueil div">
      <div class="card border rounded ">
        <img src="https://cdn.discordapp.com/attachments/1178634390830579752/1179575948421640242/moi.png?ex=657a48b5&is=6567d3b5&hm=97d290d4b53a356d073667237e379c52935ae28a728f2af2fca6bfff42577b4d&" class="card-img-top rounded-circle" alt="Flo">
        <div class="card-body d-flex flex-column p-3">
          <h5 class="card-title">Flo</h5>
          <p class="card-text flex-grow-1">"Miaou Mia Mia"</p>
        </div>
      </div>
    </div>
    <!-- Membre 5 : Robin -->
    <div class="col-md-4 mb-4 carrejaune_accueil div">
      <div class="card border rounded ">
        <img src="https://cdn.discordapp.com/attachments/1178634390830579752/1179575949063376896/robin.png?ex=657a48b5&is=6567d3b5&hm=3e393023ca9b12b73eef7a1d0bd69eab307a13faf5c42b0c75ee1d5d0a7e464c&" class="card-img-top rounded-circle" alt="Robin">
        <div class="card-body d-flex flex-column p-3">
          <h5 class="card-title">Robin Potin Couffin</h5>
          <p class="card-text flex-grow-1">"Miaou Mia"</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/contact.html.erb
<div class="container my-5">
  <h1 class="text-center mb-4">Contactez-nous !</h1>
  <p class="text-center">
    Avez-vous des questions ou des préoccupations ? N'hésitez pas à nous contacter. Nous sommes là pour vous aider.
  </p>
  <div class="row justify-content-center">
    <div class="col-md-8">
      <form>
        <div class="mb-3">
          <label for="name" class="form-label">Ton patronyme</label>
          <input type="text" class="form-control" id="name" placeholder="Entrez votre nom">
        </div>
        <div class="mb-3">
          <label for="email" class="form-label">Ton adresse des Internets</label>
          <input type="email" class="form-control" id="email" placeholder="Entrez votre email">
        </div>
        <div class="mb-3">
          <label for="message" class="form-label">Ton argumentaire</label>
          <textarea class="form-control" id="message" rows="5" placeholder="Votre message ici"></textarea>
        </div>
        <div class="text-center">
          <button type="submit" class="btn btn-primary">Envoyer</button>
        </div>
      </form>
    </div>
  </div>
  <p class="text-center mt-4">
    Vous pouvez nous joindre par email à <a href="mailto:contact@notreapp.com">contact@notreapp.com</a>, ou par téléphone au 01 23 45 67 89.
  </p>
  <p class="text-center">
    Suivez-nous également sur nos réseaux sociaux pour rester informé des dernières nouvelles et événements.
  </p>
</div>

app/views/static_pages/home.html.erb
<!-- Hero Section -->
<header class="hero-navy text-white py-5">
  <div class="container text-center">
    <h1 class="display-4">Bienvenue chez The Chatons Project</h1>
    <p class="lead">Découvrez avec nous les plus mignonnes photos de chatons ! </p>
    <%= link_to "Voir nos photos de chatons", items_path , class: "btn bg-primary text-custom-color btn-lg " %>
  </div>
</header>
<%= render 'layouts/carousel' %>

app/views/static_pages/sign_in.html.erb
<!-- Login Page with Forms and Various Controls -->
<div class="container my-4">
  <!-- Login Form -->
  <form>
    <fieldset>
      <legend class="text-center">Login to Your Account</legend>
      <!-- Email Input -->
      <div class="mb-3">
        <label for="inputEmail" class="form-label">Email address</label>
        <input type="email" class="form-control" id="inputEmail" placeholder="name@example.com">
      </div>
      <!-- Password Input -->
      <div class="mb-3">
        <label for="inputPassword" class="form-label">Password</label>
        <input type="password" class="form-control" id="inputPassword" placeholder="Password">
      </div>
      <!-- Checkboxes -->
      <div class="mb-3">
        <div class="form-check">
          <input class="form-check-input" type="checkbox" value="" id="checkRemember">
          <label class="form-check-label" for="checkRemember">
            Remember me
          </label>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="checkbox" value="" id="checkSubscribe" checked>
          <label class="form-check-label" for="checkSubscribe">
            Subscribe to newsletter
          </label>
        </div>
      </div>
      <!-- Radio Buttons -->
      <div class="mb-3">
        <label class="form-label">User Type</label>
        <div class="form-check">
          <input class="form-check-input" type="radio" name="userType" id="radioUser1" value="option1" checked>
          <label class="form-check-label" for="radioUser1">
            Regular User
          </label>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="radio" name="userType" id="radioUser2" value="option2">
          <label class="form-check-label" for="radioUser2">
            Administrator
          </label>
        </div>
      </div>
      <!-- Switches -->
      <div class="mb-3">
        <div class="form-check form-switch">
          <input class="form-check-input" type="checkbox" id="switch1">
          <label class="form-check-label" for="switch1">Enable Dark Mode</label>
        </div>
        <div class="form-check form-switch">
          <input class="form-check-input" type="checkbox" id="switch2" checked>
          <label class="form-check-label" for="switch2">Enable Notifications</label>
        </div>
      </div>
      <!-- Submit Button -->
      <button type="submit" class="btn btn-primary">Login</button>
    </fieldset>
  </form>
</div>